config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'

  get 'admins/index'

  Rails.application.routes.draw do
  get 'sessions/new'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

    resources :articles
    resources :users

    root 'welcome#index'
  end

  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :title, presence: true,
            length: {minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email = email.downcase}

  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
      format: {with: VALID_EMAIL_REGEX},
      uniqueness: {case_sensitive: false}

  validates :password, presence: true,
            length: {minimum: 6}
  has_secure_password
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include ArticlesHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "whazz", password: "root",
                               except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])

    @article.destroy

    redirect_to articles_path
  end

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "whazz", password: "root",
                               only: :destroy

  def new
    @article = Article.find(params[:article_id])
  end

  def create
    @article = Article.find(params[:article_id])
    if @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    else
      render 'new'
    end


  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

    @comment.destroy

    redirect_to article_path(@article)
  end

  private
    def comment_params
      #params[:comment][:commenter] = @current_user.name
      #params.require(:comment).permit(:body)

      comment_values = {
          :commenter => current_user.name,
          :body => params[:comment][:body]
      }
      return comment_values
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:previous_article_page] = request.env['HTTP_REFERER']
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      #login the user
      log_in user
      flash[:success] = "You have successfully been logged in."

      if admin_logged_in?
        redirect_to admins_index_path
      elsif session[:previous_article_page]
        redirect_to session[:previous_article_page]
      else
        redirect_to articles_path
      end
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      #the user has been saved successfully
      log_in @user
      flash[:success] = "Profile successfully saved. Head on down to the comments section."
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar img-circle")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def admin_logged_in?
    if current_user && @current_user == User.find_by(email: "admin@root.com")
      true
    else
      false
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/index.html.erb
<h1>Welcome back, Admin.</h1>

<h2>This is the control tower that powers the blog.</h2>

<%= link_to 'New Article', new_article_path, class: "btn btn-primary" %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %>
            prevented this article from being saved
          </h2>

          <ul>
            <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
        <p>
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </p>

        <p>
          <%= f.label :text %><br>
          <%= f.text_area :text%>
        </p>

        <p>
          <%= f.submit %>
        </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Articles</h1>

<%= render 'form' %>

<%= link_to 'Back to Articles', articles_path %>

app/views/articles/index.html.erb
<div class="center jumbotron">
  <p>
    <h1>Welcome To My Blog!</h1>
  </p>
  <p>
    <h3>
      <span class="text-danger"><strong>BE WARNED</strong></span> It's adviced you know when to stop.<br>
      Because yes, the articles are that good :). Have fun!
    </h3>
  </p>
</div>


<% counter = 1 %>

<% @articles.each do |article| %>
    <hr class="featurette-divider">

    <% if (counter%2) != 0 %>
        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading"><%= article.title %></h2>
            <p class="lead"><%= article.text %></p>
            <p>
              <%= link_to 'Read more', article_path(article), class: "btn btn-default" %>
            </p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-responsive center-block" data-src="", alt="Generic image placeholder">
          </div>
        </div>

    <% else %>
        <div class="row featurette">
          <div class="col-md-7 col-md-push-5">
            <h2 class="featurette-heading"><%= article.title %></h2>
            <p class="lead"><%= article.text %></p>
            <p>
              <%= link_to 'Read more', article_path(article), class: "btn btn-default" %>
            </p>
          </div>

          <div class="col-md-5 col-md-pull-7">
            <img class="featurette-image img-responsive center-block" data-src="..." alt="Generic image placeholder",
            class="img-rounded">
          </div>
        </div>
    <% end %>

    <% counter +=1 %>
<% end %>

<hr class="featurette-divider">

<div class="row">
  <div class="col-md-6">
    <%= link_to 'Home Page', root_path, class: "btn btn-primary" %>
  </div>

  <div>
    <%= link_to 'Back to Top', "#", class: "btn btn-primary" %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New Articles.</h1>

<%= render 'form' %>

<%= link_to 'View Articles', articles_path %>

app/views/articles/show.html.erb
<p>
  <h1><%= @article.title %></h1>
</p>

<div class="post">
    <div class="col-md-12">
      <div class="col-md-8 col-md-push-2">
        <p>
          <%= @article.text %>
        </p>
      </div>
    </div>
</div>

<p>
<h2>Comments</h2>
</p>

<% if @article.comments.any? %>
    <%= render @article.comments %>
<% else %>
    <p>
      <strong>No Comments. Be the first to comment below.</strong>
    </p>
<% end %>

<h2>Add Comment</h2>


<%= render 'comments/form' %>

<% if admin_logged_in? %>
    <p>
      <%= link_to 'Edit Article', edit_article_path(@article), class: "btn btn-primary" %>
    </p>
<% end %>

<p>
  <%= link_to 'Back to Articles', articles_path, class: "btn btn-primary" %>
</p>

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-md-4">
    <section class="user_info">
      <% if logged_in? %>
          <%= gravatar_for(current_user) %>
      <% end %>
        <p>
          <strong><%= comment.commenter %></strong>
        </p>

        <p>
          <%= comment.body %>
        </p>
    </section>
  </div>
</div>


<% if admin_logged_in? %>
    <p>
      <%= link_to 'Delete Comment', [comment.article, comment],
                  method: :delete,
                  data: {confirm: 'Are you sure?'} %>
    </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <p>
          <h3>
            <%= pluralize(@article.comments.errors.count, "error") %>
            prevented your comment from being posted.
          </h3>
          </p>

          <ul>
            <% @article.comments.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if logged_in? %>
        <div class="row">
          <p>
            <%= f.label :user %><br>
            <span class="form-control-static"><%= @current_user.name %></span>
          </p>

          <div class="col-md-12">
            <p class="col-md-6">
              <%= f.label :body %><br>
              <%= f.text_area :body, class: 'form-control', rows: "4" %>
            </p>
          </div>

          <p>
            <%= f.submit %>
          </p>
        </div>
    <% else %>
        <p class="login-comment">
          <div class="col-md-12">
            <div class="col-md-6">
              <div class="alert alert-info">
                Please login before you can comment.
                We promise it will only take a second.(Apologies for the inconvenience)
              </div>
            </div>
          </div>
        </p>

    <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">

  <small>
    Powered by <a href="#">Luvira Sys</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About', welcome_about_path %></li>
      <li><%= link_to 'Contact', welcome_contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'My Blog', root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', welcome_about_path %></li>
        <% if logged_in? %>
            <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Login', login_path %></li>
        <% end %>

        <% if admin_logged_in? %>
            <li><%= link_to 'Control', admins_index_path%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        This form contains <%= pluralize(@user.errors.count, "error") %>
      </div>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create account", class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome to the one place thats all about, me!</h1>

<div class="col-md-8 col-md-push-2">
  <p>
    I guess this is the place where I tell you about this blog and what it is.
    A corner of the wider web, neigh it's a home where we occasionally meet and share
    stories that make you laugh, or leisurely nod your head as you go "Yeah, me too!"
    as you read along to a post that familiarizes with you. A place where we can all come
    to blow off some steam and forget the world out there, form a community of like minded
    peeps,a family, if I may be so bold.
  </p>

  <h2>So who am i?</h2>
  <p>
    I think this is just one of those questions that separates the two kinds of people.
    You'll either give a straight answer after a few seconds, which basically means you know yourself
    and probably have you shit together. Or, your'e the other kind of folks, the people who start saying
    weird stuff like, "Could I really reduce my whole being to one sentence?" Which obviously means
    they still haven't discovered themselves.
  </p>
  <p>
    So, in reference to the kind of person i am, I think the better question is, who am I NOT? (To the one guy who didn't
    get it, this is the "weird stuff" I alluded to earlier.)
    A book lover. Yeah, I'm with a different one every week, I'm just that kinda guy..insert corky smiley here. Love spending hours watching movies, but who doesn't.
    Like the geeky guy i am, this mainly involves sci-fi movies. One being Interstellar, which if you haven't watched yet I
    seriously urge you to pick up. And of course by pick up i mean download from your favorite torrent site.
    Another of my watchable content is animes. NOT CARTOON! I'm referring to the japanese kind which i would
    have you know have very complicated plots.
    </p>
  <p>
    Okay, so what else. I do spend most of my time on my computer. Came with the territory after I chose to do
    Computer Science, which seems harder than it was earlier advertised. But I don't have much to complain about,
    Oh! Except that my class is like <span class="text-danger">90%</span> dude! I mean come on, that's 89%
    more testosterone than I would rather. Sorry, but had to get that out of my chest.
  </p>

  <h2>Reason I created this blog.</h2>

  <p>
    Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper.
    Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
  </p>
</div>

app/views/welcome/contact.html.erb
<h1>Email me at jacknkiarie@gmail.com</h1>

app/views/welcome/index.html.erb
<div class="center jumbotron">
      <% if logged_in? %>
        <h1>Hello, <%= current_user.name %>!</h1>
      <% else %>
        <h1>Hello, User.</h1>
      <% end %>
  <%= link_to 'My Blog', controller: 'articles', class: "btn btn-primary" %>
</div>